import streamlit as st
import requests
import os

# Sayfa Ayarları
st.set_page_config(page_title="Patient Dashboard - Basic Agent", page_icon="👤", layout="wide")

st.title("👤 Patient Dashboard")
st.markdown("### Basic Agent: Reflection Loop (Generator → Critic)")
st.divider()

# Sidebar Information
st.sidebar.info(
    "This dashboard allows patients to input their symptoms or lab results and receive a medical summary generated by the Basic Agent. The agent uses a reflection loop where the Generator creates a draft summary and the Critic reviews it for accuracy and relevance before final approval."
)

# API URL Configuration (Docker or Local)
API_URL = os.getenv("API_URL", "http://localhost:8000")

# Input Section
col_input, col_output = st.columns([1, 1])

with col_input:
    st.subheader("📋 Patient Input")
    patient_input = st.text_area(
        "Enter symptoms or lab results:",
        height=300,
        placeholder="Example: 45-year-old male patient, 3-day history of severe headache (9/10), photophobia, neck stiffness..."
    )
    
    analyze_btn = st.button("Analyze with Agent", type="primary", use_container_width=True)

with col_output:
    st.subheader("🩺 Analysis Result")
    
    if analyze_btn:
        if not patient_input:
            st.warning("Please enter symptoms or lab results first.")
        else:
            # Spinner: Generator → Critic döngüsü çalışırken gösterilir
            with st.spinner("Generator is creating draft and Critic is reviewing..."):
                try:
                    response = requests.post(f"{API_URL}/analyze", json={"text": patient_input}, timeout=60)
                    
                    if response.status_code == 200:
                        data = response.json()
                        st.success("Analysis Completed!")
                        
                        st.markdown("#### Final Approved Medical Summary")
                        st.info(data.get("final_summary", "Summary not available."))
                        
                        # Agent Thinking History
                        with st.expander("🔍 View Agent Thinking History"):
                            history = data.get("history", [])
                            for msg in history:
                                if "[GENERATOR]" in msg:
                                    st.markdown(f"**🤖 Generator:**\n{msg.replace('[GENERATOR]:', '')}")
                                elif "[CRITIC]" in msg:
                                    st.markdown(f"**⚖️ Critic:**\n`{msg.replace('[CRITIC]:', '')}`")
                                st.divider()
                    else:
                        st.error(f"API Error: {response.status_code} - {response.text}")
                        
                except Exception as e:
                    st.error(f"Connection Error: {e}")
    else:
        st.write("Analysis results will appear here.")

# Example Input Button (For Quick Testing)
if not patient_input:
    if st.button("Fill Example Data"):
        st.session_state.sample_text = "Patient is 45-year-old male with 3-day history of: severe headache, neck stiffness, Temperature 38.7C, WBC 14,200 (elevated)."
        st.rerun()
